/*

 LEVELTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 23

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define LevelTilesBank 0

/* Super Gameboy palette 0 */
#define LevelTilesSGBPal0c0 6076
#define LevelTilesSGBPal0c1 8935
#define LevelTilesSGBPal0c2 6596
#define LevelTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define LevelTilesSGBPal1c0 6076
#define LevelTilesSGBPal1c1 8935
#define LevelTilesSGBPal1c2 6596
#define LevelTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define LevelTilesSGBPal2c0 6076
#define LevelTilesSGBPal2c1 8935
#define LevelTilesSGBPal2c2 6596
#define LevelTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define LevelTilesSGBPal3c0 6076
#define LevelTilesSGBPal3c1 8935
#define LevelTilesSGBPal3c2 6596
#define LevelTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define LevelTilesCGBPal0c0 28634
#define LevelTilesCGBPal0c1 32642
#define LevelTilesCGBPal0c2 124
#define LevelTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define LevelTilesCGBPal1c0 28634
#define LevelTilesCGBPal1c1 1259
#define LevelTilesCGBPal1c2 124
#define LevelTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define LevelTilesCGBPal2c0 32767
#define LevelTilesCGBPal2c1 31636
#define LevelTilesCGBPal2c2 32389
#define LevelTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define LevelTilesCGBPal3c0 6076
#define LevelTilesCGBPal3c1 8935
#define LevelTilesCGBPal3c2 6596
#define LevelTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define LevelTilesCGBPal4c0 6076
#define LevelTilesCGBPal4c1 8935
#define LevelTilesCGBPal4c2 6596
#define LevelTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define LevelTilesCGBPal5c0 6076
#define LevelTilesCGBPal5c1 8935
#define LevelTilesCGBPal5c2 6596
#define LevelTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define LevelTilesCGBPal6c0 6076
#define LevelTilesCGBPal6c1 8935
#define LevelTilesCGBPal6c2 6596
#define LevelTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define LevelTilesCGBPal7c0 6076
#define LevelTilesCGBPal7c1 8935
#define LevelTilesCGBPal7c2 6596
#define LevelTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char LevelTilesCGB[];
/* Start of tile array. */
extern unsigned char LevelTiles[];

/* End of LEVELTILES.H */
