/*

 LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : LevelTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level1Width 20
#define Level1Height 18
#define Level1Bank 0

#define Level1 Level1PLN0
extern unsigned char Level1PLN0[];
extern unsigned char Level1PLN1[];

/* End of LEVEL1.H */
