/*

 LEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : LevelTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level2Width 20
#define Level2Height 18
#define Level2Bank 0

#define Level2 Level2PLN0
extern unsigned char Level2PLN0[];
extern unsigned char Level2PLN1[];

/* End of LEVEL2.H */
