/*

 LEVEL3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\University\Year 2 Modules\Native Programming and Compilation\Coursework\Assignment 1\GameboyCode\Artemisia's Quest\LevelTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level3Width 20
#define Level3Height 18
#define Level3Bank 0

#define Level3 Level3PLN0
extern unsigned char Level3PLN0[];
extern unsigned char Level3PLN1[];

/* End of LEVEL3.H */
